# Generated by Django 5.0.4 on 2024-05-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='rentEndDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='rent',
            name='rentStartDate',
            field=models.DateTimeField(),
        ),
    ]
