# Generated by Django 5.0.4 on 2024-05-04 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_alter_rent_iha_alter_rent_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rent',
            options={'permissions': (('list_rent', ''), ('list_my_rents', ''), ('list_admin_rents', ''), ('delete_my_rent', ''), ('delete_admin_rent', ''), ('update_my_rent', ''), ('update_admin_rent', ''))},
        ),
    ]
