# Generated by Django 5.0.4 on 2024-05-05 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0004_alter_rent_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rent',
            options={'permissions': (('list_my_rents', 'Can list myrent'), ('list_admin_rents', 'Can list rent'), ('delete_my_rent', 'Can delete myrent'), ('delete_admin_rent', 'Can delete rent'), ('update_my_rent', 'Can update myrent'), ('update_admin_rent', 'Can update rent'))},
        ),
    ]
