# Generated by Django 5.0.4 on 2024-05-05 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iha', '0003_alter_iha_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iha',
            options={'permissions': (('list_ihas', 'Can list iha'), ('list_ihas_data', 'Can list iha data'), ('update_iha', 'Can update iha'))},
        ),
    ]
